//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopOnline_ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Comments = new HashSet<Comment>();
            this.FILES = new HashSet<FILE>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        public int BookID { get; set; }
        [Required(ErrorMessage = "BookName can't be empty")]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "Book name must be a string and the first letter must be uppercase")]
        public string BookName { get; set; }
        [Required(ErrorMessage = "Price can't be empty")]

        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Description can't be empty")]

        public string Description { get; set; }
        //[Required(ErrorMessage = "CreatedDate can't be empty")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        //[Required(ErrorMessage = "Status can't be empty")]
        public bool Status { get; set; }
        [Required(ErrorMessage = "GenreID can't be empty")]
        public Nullable<int> GenreID { get; set; }
        [Required(ErrorMessage = "AuthorID can't be empty")]
        public Nullable<int> AuthorID { get; set; }

        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE> FILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
