//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopOnline_ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int CommentID { get; set; }
        [Required(ErrorMessage = "Rating can't be empty")]
        public Nullable<double> Rating { get; set; }
        [Required(ErrorMessage = "Type something to send")]
        //[RegularExpression(@"^[a-zA-Z'\s]*$", ErrorMessage = "Content must be a string")]
        public string Content { get; set; }
        [Required(ErrorMessage = "BookID can't be empty")]
        public Nullable<int> BookID { get; set; }
        [Required(ErrorMessage = "UserID can't be empty")]
        public Nullable<int> UserID { get; set; }

        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
