//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopOnline_ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAQ
    {
        public int ContactID { get; set; }
        [Required(ErrorMessage = "Question can't be empty")]
        public string Question { get; set; }

        [Required, StringLength(2000, MinimumLength = 500, ErrorMessage = "Must be at least 500 characters long.")]      
        public string Answer { get; set; }
    }
}
