//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopOnline_ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        [Required(ErrorMessage = "Name can't be empty")]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "First name must be letters and must be uppercase")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Phone can't be empty")]
        [DataType(DataType.PhoneNumber)]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Email can't be empty")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email doesn't look like a valid email address.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Description can't be empty")]
        //[RegularExpression(@"^[a-zA-Z'\s]*$", ErrorMessage = "Description must be a string")]
        public string Description { get; set; }
        //[Required(ErrorMessage = "CreatedDate can't be empty")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        //[Required(ErrorMessage = "Status can't be empty")]
        public bool Status { get; set; }
    }
}
